# fly.toml app configuration file generated for rough-breeze-138 on 2023-09-26T09:27:18Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rough-breeze-138"
primary_region = "phx"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
